[tool.black]
line-length = 88
target-version = ["py311", "py312"]
extend-exclude = '''
(
  (^|/)\.venv
| (^|/)venv
| (^|/)\.checkiopy
| (^|/)build
| (^|/)dist
| (^|/)\.mypy_cache
| (^|/)\.ruff_cache
| (^|/)\.pytest_cache
)
'''

[tool.ruff]
line-length = 120
target-version = "py311"
exclude = [".venv", "venv", ".checkiopy", "build", "dist", ".mypy_cache", ".ruff_cache", ".pytest_cache"]
# Przykładowe reguły – dopasuj pod siebie:
select = ["E", "F", "I", "UP", "B"]
ignore = []

[tool.mypy]
python_version = "3.11"
exclude = '(\.venv|venv|\.checkiopy|build|dist|\.mypy_cache|\.ruff_cache|\.pytest_cache)/'
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
